# infra/clusters/cluster-argo/cluster.yaml
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: argo-cluster
  namespace: fleet-default
spec:
  cloudCredentialSecretName: cattle-global-data:cc-kk8zm
  clusterAgentDeploymentCustomization:
    appendTolerations: []
    overrideAffinity: {}
    overrideResourceRequirements: {}
  defaultPodSecurityAdmissionConfigurationTemplateName: ''
  fleetAgentDeploymentCustomization:
    appendTolerations: []
    overrideAffinity: {}
    overrideResourceRequirements: {}
  kubernetesVersion: v1.34.5+rke2r1
  localClusterAuthEndpoint:
    enabled: false
  rkeConfig:
    additionalManifest: |-
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: harvester-cloud-provider
        namespace: kube-system
      spec:
        targetNamespace: kube-system
        bootstrap: true
        repo: https://raw.githubusercontent.com/rancher/charts/dev-v2.9
        chart: harvester-cloud-provider
        version: 104.0.2+up0.2.6
        helmVersion: v3
        valuesContent: |-
          global:
            cattle:
              clusterName: argo-cluster
    chartValues:
      harvester-cloud-provider:
        global:
          cattle:
            clusterName: argo-cluster
        cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
      rke2-calico: {}
    dataDirectories:
      k8sDistro: ''
      provisioning: ''
      systemAgent: ''
    etcd:
      disableSnapshots: true
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePools:
      - name: pool1
        etcdRole: true
        controlPlaneRole: true
        workerRole: true
        hostnamePrefix: ''
        quantity: 1
        unhealthyNodeTimeout: 0m
        machineConfigRef:
          kind: HarvesterConfig
          name: nc-argo-cluster-pool1-t7jzm
        drainBeforeDelete: true
        labels: {}
    machineSelectorConfig:
      - config:
          cloud-provider-config: secret://fleet-default:harvesterconfigct72s
          cloud-provider-name: harvester
          protect-kernel-defaults: false
    networking: {}
    registries:
      configs: {}
      mirrors: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
  machineSelectorConfig:
    - config: {}
---
apiVersion: rke-machine-config.cattle.io/v1
kind: HarvesterConfig
metadata:
  name: nc-argo-cluster-pool1-t7jzm
  namespace: fleet-default
  generateName: nc-argo-cluster-pool1-
spec:
  cpuCount: '2'
  cpuPinning: false
  diskInfo: '{"disks":[{"imageName":"images/image-crplc","bootOrder":1,"size":40}]}'
  diskSize: '0'
  memorySize: '4'
  reservedMemorySize: '-1'
  vmNamespace: techday
  sshUser: sles
  sshPort: '22'
  networkInfo: '{"interfaces":[{"networkName":"network/vm-net","macAddress":""}]}'
  networkData: >-
    I2Nsb3VkLWNvbmZpZwpuZXR3b3JrOgogIHZlcnNpb246IDEKICBjb25maWc6CiAgICAtIHR5cGU6IHBoeXNpY2FsCiAgICAgIG5hbWU6IGV0aDAKICAgICAgc3VibmV0czoKICAgICAgICAtIHR5cGU6IGRoY3A=
  userData: >-
    I2Nsb3VkLWNvbmZpZwpjaHBhc3N3ZDoKICBsaXN0OiB8CiAgICByb290OiQ2JFNhbFRzYUx0JDQ3d0pnT0YyQVpGS1lpU3hES004YmVSeUlNNUpZZzI4bGdFaXJ5MjVWNUZiQzRuRHVrOU9IcHhDMFh0c0prWTFPWVpOWUhXTW5UTGhYc2dQd0w1U1MuCiAgICBzbGVzOiQ2JFNhbFRzYUx0JDQ3d0pnT0YyQVpGS1lpU3hES004YmVSeUlNNUpZZzI4bGdFaXJ5MjVWNUZiQzRuRHVrOU9IcHhDMFh0c0prWTFPWVpOWUhXTW5UTGhYc2dQd0w1U1MuCiAgZXhwaXJlOiBGYWxzZQpydW5jbWQ6CiAgLSBzdXNlY29ubmVjdCAtZSBlcmljby5tZW5kb25jYUBzdXNlLmNvbSAtciBJTlRFUk5BTC1VU0UtT05MWS1kYmI5LTY1ZjEKcGFja2FnZXM6CiAgLSBpcHRhYmxlcwogIC0gY3VybAogIC0gd2dldA==
