# infra/clusters/cluster-argo/cluster.yaml
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: cluster-argo
  namespace: fleet-default
spec:
  cloudCredentialSecretName: cattle-global-data:cc-kl7d9
  defaultPodSecurityAdmissionConfigurationTemplateName: ''
  kubernetesVersion: v1.34.4+rke2r1
  localClusterAuthEndpoint:
    enabled: false
  rkeConfig:
    chartValues:
      harvester-cloud-provider:
        global:
          cattle:
            clusterName: cluster-argo
        cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
      rke2-calico: {}
    dataDirectories:
      k8sDistro: ''
      provisioning: ''
      systemAgent: ''
    etcd:
      disableSnapshots: true
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePools:
      - name: argo
        etcdRole: true
        controlPlaneRole: true
        workerRole: true
        hostnamePrefix: ''
        quantity: 1
        unhealthyNodeTimeout: 0m
        machineConfigRef:
          kind: HarvesterConfig
          name: nc-cluster-argo-argo-pmmvp # <--- LIGAÇÃO COM A MÁQUINA ABAIXO
        drainBeforeDelete: true
    machineSelectorConfig:
      - config:
          cloud-provider-config: secret://fleet-default:harvesterconfig5swf8
          cloud-provider-name: harvester
          protect-kernel-defaults: false
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
---
apiVersion: rke-machine-config.cattle.io/v1
kind: HarvesterConfig
metadata:
  name: nc-cluster-argo-argo-pmmvp # TEM DE SER IGUAL AO NOME ACIMA
  namespace: fleet-default
cpuCount: '2'
cpuPinning: false
diskInfo: '{"disks":[{"imageName":"labs/image-6f7mx","bootOrder":1,"size":40}]}'
enableEfi: false
enableSecureBoot: false
enableTpm: false
isolateEmulatorThread: false
memorySize: '4'
networkData: >-
  I2Nsb3VkLWNvbmZpZwpuZXR3b3JrOgogIHZlcnNpb246IDEKICBjb25maWc6CiAgICAtIHR5cGU6IHBoeXNpY2FsCiAgICAgIG5hbWU6IGV0aDAKICAgICAgc3VibmV0czoKICAgICAgICAtIHR5cGU6IGRoY3A=
networkInfo: '{"interfaces":[{"networkName":"default/local-net","macAddress":""}]}'
reservedMemorySize: '-1'
sshPort: '22'
sshUser: sles
userData: >-
  I2Nsb3VkLWNvbmZpZwpjaHBhc3N3ZDoKICBsaXN0OiB8CiAgICByb290OiQ2JFNhbFRzYUx0JDQ3d0pnT0YyQVpGS1lpU3hES004YmVSeUlNNUpZZzI4bGdFaXJ5MjVWNUZiQzRuRHVrOU9IcHhDMFh0c0prWTFPWVpOWUhXTW5UTGhYc2dQd0w1U1MuCiAgICBzbGVzOiQ2JFNhbFRzYUx0JDQ3d0pnT0YyQVpGS1lpU3hES004YmVSeUlNNUpZZzI4bGdFaXJ5MjVWNUZiQzRuRHVrOU9IcHhDMFh0c0prWTFPWVpOWUhXTW5UTGhYc2dQd0w1U1MuCiAgZXhwaXJlOiBGYWxzZQpwYWNrYWdlczoKICAtIGlwdGFibGVzCiAgLSBjdXJsCiAgLSB3Z2V0CnJ1bmNtZDoKICAtIHN1c2Vjb25uZWN0IC1lIGVyaWNvLm1lbmRvbmNhQHN1c2UuY29tIC1yIElOVEVSTkFMLVVTRS1PTkxZLWRiYjktNjVmMQogIC0gc2ggLWMgJ2VjaG8gIjE5Mi4xNjguODYuMTUxIHJhbmNoZXIuY29udGV1ZG9xdWVzdGlvbmF2ZWwub3JnIHJhbmNoZXIiID4+IC9ldGMvaG9zdHMn
vmNamespace: techday