apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
data:
  index.html: |
    <html>
      <body style="background-color: #e6ffe6; text-align: center; padding: 50px; font-family: sans-serif;">
        <h1>🚀 Bem-vindo ao Ambiente de PRODUÇÃO!</h1>
        <p>Entregue automaticamente via <b>Argo CD</b> + <b>Kustomize</b>.</p>
      </body>
    </html>
