apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Herdar da base
resources:
  - ../../base

# Aplicar as alterações
patchesStrategicMerge:
  - patch-replicas.yaml
  - configmap-patch.yaml

# Modificadores globais mágicos do Kustomize
namePrefix: prod-
commonLabels:
  env: producao
